#define NITRODESERT_ATMOS GAS_O2 + "=2.2;" + GAS_N2 + "=98.5;" + GAS_CO2 + "=4.6;" + GAS_WATER_VAPOR + "=1.1;TEMP=270.65"
#define NITRODESERT_ATMOS_CAVE LAVALAND_DEFAULT_ATMOS

#define ZTRAIT_DUNEPOST_RUINS "Dunepost Ruins"
#define ZTRAIT_DUNEPOST_RUINS_UNDERGROUND "Dunepost Ruins Underground"
